
server:
  port: 8090

spring:
  h2:
    console:
      enabled: true
      path: /h2
  jpa:
    database: h2
  datasource:
    url: jdbc:h2:~/test
    username: sa
    password: null
  application:
    name: report-data-service
 
logging:
  level:
    root: ERROR
    org.springframework.web: INFO
    com.assignment.reportservice: INFO
    org.hibernate: ERROR
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: reportdata-service.log
  
jan:
 filepath: D:\Nagaraj\Crealytics\2018_01_report.csv
feb:
 filepath: D:\Nagaraj\Crealytics\2018_02_report.csv
 